blog_homepage:
    path:     /{_locale}
    defaults: { _controller: BlogBundle:Default:index, _locale:ru }
    requirements:
            _locale: en|ru
blog_show:
    resource: "@BlogBundle/Resources/config/routing/post.yml"
    prefix:   /post
category:
    resource: "@BlogBundle/Resources/config/routing/category.yml"
    prefix: /category
