post_index:
    path:     /
    defaults: { _controller: "BlogBundle:Default—ã:index" }
    methods:  GET

post_show:
    path:     /{id}/show
    defaults: { _controller: "BlogBundle:Default:show" }
    methods:  GET

post_new:
    path:     /new
    defaults: { _controller: "BlogBundle:Default:create" }
    methods:  [GET, POST]

post_edit:
    path:     /{id}/edit
    defaults: { _controller: "BlogBundle:Default:edit" }
    methods:  [GET, POST]

post_delete:
    path:     /{id}/delete
    defaults: { _controller: "BlogBundle:Default:delete" }
    methods:  DELETE